export const crewStatus = {
  CREW_BUSY: 'BUSY',
  CREW_BREAK: 'BREAK',
  CREW_READY: 'READY',
  CREW_OFFLINE: 'OFFLINE',
  CREW_ASKED: 'ASKED',
  CREW_DRIVE_BACK: 'DRIVE_BACK',
}

export const eventStatus = {
  EVENT_NEW: 'NEW',
  EVENT_INSPECTION: 'INSPECTION',
  EVENT_ON_THE_ROAD: 'ON_THE_ROAD',
  EVENT_FINISHED: 'FINISHED',
  EVENT_INSPECTION_DONE: 'INSPECTION_DONE',
  EVENT_CANCELLED: 'CANCELLED',
  EVENT_CANCELLED_BY_CLIENT: 'CANCELLED_BY_CLIENT',
  EVENT_CANCELLED_BY_CLIENT_CONFIRMED: 'CANCELLED_BY_CLIENT_CONFIRMED',
  EVENT_WAIT_FOR_APPROVAL: 'WAIT_FOR_APPROVAL',
  EVENT_REQUESTS: 'REQUESTS',

}

export const permissionStatus = {
  PERMISSION_COMPLETE: 'COMPLETE',
  PERMISSION_REJECTED: 'REJECTED',
  PERMISSION_CANCELLED: 'CANCELLED',
  PERMISSION_ALLOWED: 'ALLOWED',
  PERMISSION_ASKED: 'ASKED',
}

export const helpStatus = {
  HELP_NEW: 'NEW',
  HELP_COMPLETED: 'COMPLETED',
}