export const filterTemplates = [
  {
    id: 1,
    filterName: "View 2 with filter",
    filterShortName: "FAV1",
    saveToFavorite: true,
    saveToMenu: true,
    date: "2021-06-09 22:00",
    operator: "1",
    object: "1",
    objectAddress: "some address",
    type: "1",
    group: "1",
    status: "1",
    reason: "1",
    crew: "1",
    driver: "1",
    inTime: "1",
    showDate: true,
    showObject: true,
    showName: true,
    showCrew: true,
    showInTime: true,
    showReactionTime: true,
    showTimeInObject: true,
    showStatus: true,
    showReason: true
  },
];
