export const Modems = [
  {
    'id': '1',
    'number': '5561651651',
    'objectName': 'Objekto Pavadinimas 1',
    'objectNo': 'TAIP',
    'contractNo': 'SPS-005415',
    'status': 'disconnected',
  },
  {
    'id': '2',
    'number': '5561651652',
    'objectName': 'Objekto Pavadinimas 2',
    'objectNo': 'TAIP',
    'contractNo': 'SPS-005415',
    'status': 'disconnected',
  },
  {
    'id': '3',
    'number': '5561651653',
    'objectName': 'Objekto Pavadinimas',
    'objectNo': 'TAIP',
    'contractNo': 'SPS-005415',
    'status': 'disconnected',
  },
  {
    'id': '4',
    'number': '5561651654',
    'objectName': 'Objekto Pavadinimas',
    'objectNo': 'TAIP',
    'contractNo': 'SPS-005415',
    'status': 'disconnected',
  },
  {
    'id': '5',
    'number': '5561651655',
    'objectName': 'Objekto Pavadinimas',
    'objectNo': 'TAIP',
    'contractNo': 'SPS-005415',
    'status': 'disconnected',
  },
  {
    'id': '6',
    'number': '5561651656',
    'objectName': 'Objekto Pavadinimas',
    'objectNo': 'TAIP',
    'contractNo': 'SPS-005419',
    'status': 'disconnected',
  },
  {
    'id': '7',
    'number': '5561651657',
    'objectName': 'Objekto Pavadinimas',
    'objectNo': 'TAIP',
    'contractNo': 'SPS-005418',
    'status': 'disconnected',
  },
  {
    'id': '8',
    'number': '5561651658',
    'objectName': 'Objekto Pavadinimas',
    'objectNo': 'TAIP',
    'contractNo': 'SPS-005417',
    'status': 'disconnected',
  },
  {
    'id': '9',
    'number': '5561651659',
    'objectName': 'Objekto Pavadinimas',
    'objectNo': 'Ne',
    'contractNo': 'SPS-005416',
    'status': 'disconnected',
  },
];
