export const Modems = [
  {
    "number": "5561651651",
    "objectName": "Objekto Pavadinimas 1",
    "objectNo": "TAIP",
    "contractNo": "SPS-005415",
    "status": "disconnected",
  },
  {
    "number": "5561651652",
    "objectName": "Objekto Pavadinimas 2",
    "objectNo": "TAIP",
    "contractNo": "SPS-005415",
    "status": "disconnected",
  },
  {
    "number": "5561651653",
    "objectName": "Objekto Pavadinimas",
    "objectNo": "TAIP",
    "contractNo": "SPS-005415",
    "status": "disconnected",
  },
  {
    "number": "5561651654",
    "objectName": "Objekto Pavadinimas",
    "objectNo": "TAIP",
    "contractNo": "SPS-005415",
    "status": "disconnected",
  },
  {
    "number": "5561651655",
    "objectName": "Objekto Pavadinimas",
    "objectNo": "TAIP",
    "contractNo": "SPS-005415",
    "status": "disconnected",
  },
  {
    "number": "5561651656",
    "objectName": "Objekto Pavadinimas",
    "objectNo": "TAIP",
    "contractNo": "SPS-005419",
    "status": "disconnected",
  },
  {
    "number": "5561651657",
    "objectName": "Objekto Pavadinimas",
    "objectNo": "TAIP",
    "contractNo": "SPS-005418",
    "status": "disconnected",
  },
  {
    "number": "5561651658",
    "objectName": "Objekto Pavadinimas",
    "objectNo": "TAIP",
    "contractNo": "SPS-005417",
    "status": "disconnected",
  },
  {
    "number": "5561651659",
    "objectName": "Objekto Pavadinimas",
    "objectNo": "Ne",
    "contractNo": "SPS-005416",
    "status": "disconnected",
  },
];
