export const Orders = [
  {
    "contract": "contract1",
    "city": "city1",
    "address": "address1",
    "object": "object1",
    "name": "Vardenis Pavardenis 1",
    "sentCrew": "TAIP",
  },
  {
    "contract": "contract2",
    "city": "city2",
    "address": "address2",
    "object": "object2",
    "name": "Vardenis Pavardenis 2",
    "sentCrew": "Ne",
  },
  {
    "contract": "contract3",
    "city": "city3",
    "address": "address3",
    "object": "object3",
    "name": "Vardenis Pavardenis 3",
    "sentCrew": "TAIP",
  },
  {
    "contract": "contract4",
    "city": "city4",
    "address": "address4",
    "object": "object4",
    "name": "Vardenis Pavardenis 4",
    "sentCrew": "TAIP",
  },
  {
    "contract": "contract5",
    "city": "city5",
    "address": "address5",
    "object": "object5",
    "name": "Vardenis Pavardenis 5",
    "sentCrew": "NE",
  },
  {
    "contract": "contract1",
    "city": "city1",
    "address": "address1",
    "object": "object1",
    "name": "Vardenis Pavardenis 1",
    "sentCrew": "TAIP",
  },
  {
    "contract": "contract2",
    "city": "city2",
    "address": "address2",
    "object": "object2",
    "name": "Vardenis Pavardenis 2",
    "sentCrew": "Ne",
  },
  {
    "contract": "contract3",
    "city": "city3",
    "address": "address3",
    "object": "object3",
    "name": "Vardenis Pavardenis 3",
    "sentCrew": "TAIP",
  },
  {
    "contract": "contract4",
    "city": "city4",
    "address": "address4",
    "object": "object4",
    "name": "Vardenis Pavardenis 4",
    "sentCrew": "TAIP",
  },
  {
    "contract": "contract5",
    "city": "city5",
    "address": "address5",
    "object": "object5",
    "name": "Vardenis Pavardenis 5",
    "sentCrew": "NE",
  },
  {
    "contract": "contract1",
    "city": "city1",
    "address": "address1",
    "object": "object1",
    "name": "Vardenis Pavardenis 1",
    "sentCrew": "TAIP",
  },
  {
    "contract": "contract2",
    "city": "city2",
    "address": "address2",
    "object": "object2",
    "name": "Vardenis Pavardenis 2",
    "sentCrew": "Ne",
  },
  {
    "contract": "contract3",
    "city": "city3",
    "address": "address3",
    "object": "object3",
    "name": "Vardenis Pavardenis 3",
    "sentCrew": "TAIP",
  },
  {
    "contract": "contract4",
    "city": "city4",
    "address": "address4",
    "object": "object4",
    "name": "Vardenis Pavardenis 4",
    "sentCrew": "TAIP",
  },
  {
    "contract": "contract5",
    "city": "city5",
    "address": "address5",
    "object": "object5",
    "name": "Vardenis Pavardenis 5",
    "sentCrew": "NE",
  },
];
