export const STATUS = {
  NEW: 'NEW',
  CANCELLED: 'CANCELLED',
  WAIT_FOR_APPROVAL: 'WAIT_FOR_APPROVAL',
  ON_THE_ROAD: 'ON_THE_ROAD',
  INSPECTION: 'INSPECTION',
  INSPECTION_DONE: 'INSPECTION_DONE',
  FINISHED: 'FINISHED',
};
