export const STATUS = {
  NEW: 'NEW',
  WAIT_FOR_APPROVAL: 'WAIT_FOR_APPROVAL',
  ON_THE_ROAD: 'ON_THE_ROAD',
  INSPECTION: 'INSPECTION',
  INSPECTION_DONE: 'INSPECTION_DONE',
  FINISHED: 'FINISHED',
  CANCELLED: 'CANCELLED',
  CANCELLED_BY_CLIENT: 'CANCELLED_BY_CLIENT',
  CANCELLED_BY_CLIENT_CONFIRMED: 'CANCELLED_BY_CLIENT_CONFIRMED',
};
